"""token usage models

Revision ID: 2e416d54e8ee
Revises: ac7768abf755
Create Date: 2026-03-14 15:45:29.043802

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e416d54e8ee"
down_revision: Union[str, Sequence[str], None] = "ac7768abf755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokenbalance",
        sa.Column("subject_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("period_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("used_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llmmodel.id"],
        ),
        sa.PrimaryKeyConstraint("subject_type", "subject_id", "period_key", "model_id"),
    )
    op.create_table(
        "tokenbucket",
        sa.Column("subject_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("parent_bucket_id", sa.Uuid(), nullable=True),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("token_limit", sa.Integer(), nullable=False),
        sa.Column("period_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llmmodel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_bucket_id"],
            ["tokenbucket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_type",
            "subject_id",
            "model_id",
            "token_limit",
            "period_type",
            name="idx_token_bucket_unique_constraint",
        ),
    )
    op.create_index(
        op.f("ix_tokenbucket_subject_id"), "tokenbucket", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_tokenbucket_subject_type"),
        "tokenbucket",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "tokenledger",
        sa.Column("bucket_id", sa.Uuid(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=True),
        sa.Column("period_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["tokenbucket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tokenreservation",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_id", sa.Uuid(), nullable=False),
        sa.Column("reserved_tokens", sa.Integer(), nullable=False),
        sa.Column("period_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["tokenbucket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokenreservation_request_id"),
        "tokenreservation",
        ["request_id"],
        unique=False,
    )
    op.add_column(
        "llmmodel",
        sa.Column(
            "context_window",
            sa.Integer(),
            server_default=sa.text("128000"),
            nullable=True,
        ),
    )
    op.add_column(
        "llmmodel",
        sa.Column(
            "max_output_tokens",
            sa.Integer(),
            server_default=sa.text("4096"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llmmodel", "max_output_tokens")
    op.drop_column("llmmodel", "context_window")
    op.drop_index(op.f("ix_tokenreservation_request_id"), table_name="tokenreservation")
    op.drop_table("tokenreservation")
    op.drop_table("tokenledger")
    op.drop_index(op.f("ix_tokenbucket_subject_type"), table_name="tokenbucket")
    op.drop_index(op.f("ix_tokenbucket_subject_id"), table_name="tokenbucket")
    op.drop_table("tokenbucket")
    op.drop_table("tokenbalance")
    # ### end Alembic commands ###
