"""allow model usage logs without conversation or message

Revision ID: 3c79618f970e
Revises: e1a5bd756804
Create Date: 2026-02-02 16:30:00.582779

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c79618f970e"
down_revision: Union[str, Sequence[str], None] = "e1a5bd756804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modelusagelog", "conversation_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "modelusagelog", "message_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modelusagelog", "message_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "modelusagelog", "conversation_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
