"""llm model credentials

Revision ID: 6a03c0dd0c36
Revises: 2e416d54e8ee
Create Date: 2026-04-02 10:22:15.814686

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a03c0dd0c36"
down_revision: Union[str, Sequence[str], None] = "2e416d54e8ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llmcredential",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "encrypted_payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "llmmodel",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("llmmodel", sa.Column("credential_id", sa.Uuid(), nullable=True))

    # Backfill slugs from the existing model name
    op.execute(
        sa.text(
            """
            UPDATE llmmodel
            SET slug = COALESCE(
                NULLIF(
                    TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER(name), '[^a-z0-9]+', '-', 'g')),
                    ''
                ),
                CONCAT('model-', SUBSTRING(REPLACE(CAST(id AS TEXT), '-', '') FROM 1 FOR 8))
            )
            WHERE slug IS NULL OR BTRIM(slug) = ''
            """
        )
    )
    op.alter_column(
        "llmmodel",
        "slug",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )

    op.drop_constraint(op.f("llmmodel_name_key"), "llmmodel", type_="unique")
    op.create_index(
        op.f("ix_llmmodel_credential_id"), "llmmodel", ["credential_id"], unique=False
    )
    op.create_index(op.f("ix_llmmodel_slug"), "llmmodel", ["slug"], unique=True)
    op.create_unique_constraint(
        "unique_llm_model_provider_name_credential",
        "llmmodel",
        ["provider", "name", "credential_id"],
    )
    op.create_foreign_key(
        "fk_model_credential", "llmmodel", "llmcredential", ["credential_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_model_credential", "llmmodel", type_="foreignkey")
    op.drop_constraint(
        "unique_llm_model_provider_name_credential", "llmmodel", type_="unique"
    )
    op.drop_index(op.f("ix_llmmodel_slug"), table_name="llmmodel")
    op.drop_index(op.f("ix_llmmodel_credential_id"), table_name="llmmodel")
    op.create_unique_constraint(
        op.f("llmmodel_name_key"),
        "llmmodel",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("llmmodel", "credential_id")
    op.drop_column("llmmodel", "slug")
    op.drop_table("llmcredential")
    # ### end Alembic commands ###
