"""add organization, team and division table

Revision ID: 7b09102bca31
Revises: 3c79618f970e
Create Date: 2026-02-22 20:22:22.538972

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b09102bca31"
down_revision: Union[str, Sequence[str], None] = "3c79618f970e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )

    op.create_table(
        "division",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "name", name="unique_division_organization_name"
        ),
        sa.UniqueConstraint(
            "organization_id", "slug", name="unique_division_organization_slug"
        ),
    )

    op.create_index(op.f("ix_division_name"), "division", ["name"], unique=False)
    op.create_index(op.f("ix_division_slug"), "division", ["slug"], unique=False)

    op.create_table(
        "team",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("division_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("division_id", "name", name="unique_team_division_name"),
        sa.UniqueConstraint("division_id", "slug", name="unique_team_division_slug"),
    )

    op.create_index(op.f("ix_team_division_id"), "team", ["division_id"], unique=False)
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=False)
    op.create_index(op.f("ix_team_slug"), "team", ["slug"], unique=False)

    op.create_table(
        "userteamlink",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "team_id"),
    )

    op.add_column("user", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.add_column("user", sa.Column("division_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_user_division_id"), "user", ["division_id"], unique=False)
    op.create_index(
        op.f("ix_user_organization_id"), "user", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        "fk_user_organization", "user", "organization", ["organization_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_user_division", "user", "division", ["division_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_organization", "user", type_="foreignkey")
    op.drop_constraint("fk_user_division", "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_organization_id"), table_name="user")
    op.drop_index(op.f("ix_user_division_id"), table_name="user")
    op.drop_column("user", "division_id")
    op.drop_column("user", "organization_id")
    op.drop_table("userteamlink")
    op.drop_index(op.f("ix_team_slug"), table_name="team")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_index(op.f("ix_team_division_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(op.f("ix_division_slug"), table_name="division")
    op.drop_index(op.f("ix_division_name"), table_name="division")
    op.drop_table("division")
    op.drop_table("organization")
    # ### end Alembic commands ###
