"""change bucket unique constraint

Revision ID: 7ed08a87272a
Revises: 6a03c0dd0c36
Create Date: 2026-04-06 10:37:08.546507

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ed08a87272a"
down_revision: Union[str, Sequence[str], None] = "6a03c0dd0c36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("idx_token_bucket_unique_constraint"), "tokenbucket", type_="unique"
    )
    op.create_unique_constraint(
        "unique_token_bucket_subject_model",
        "tokenbucket",
        ["subject_type", "subject_id", "model_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_token_bucket_subject_model", "tokenbucket", type_="unique"
    )
    op.create_unique_constraint(
        op.f("idx_token_bucket_unique_constraint"),
        "tokenbucket",
        ["subject_type", "subject_id", "model_id", "token_limit", "period_type"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
