"""add status for knowledge base and file

Revision ID: 8676dc61378a
Revises: 147ea9e263c3
Create Date: 2026-03-08 00:49:48.948093

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8676dc61378a'
down_revision: Union[str, Sequence[str], None] = '147ea9e263c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileknowledgebaselink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('fileknowledgebaselink', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('fileknowledgebaselink', sa.Column('status', sa.String(), server_default='pending', nullable=True))
    op.add_column('fileknowledgebaselink', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('knowledgebase', sa.Column('status', sa.String(), server_default='pending', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'status')
    op.drop_column('fileknowledgebaselink', 'error_message')
    op.drop_column('fileknowledgebaselink', 'status')
    op.drop_column('fileknowledgebaselink', 'updated_at')
    op.drop_column('fileknowledgebaselink', 'created_at')
    # ### end Alembic commands ###
