"""add conversation table

Revision ID: 918bdd620c98
Revises: 501141005151
Create Date: 2025-12-27 19:56:33.631171

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "918bdd620c98"
down_revision: Union[str, Sequence[str], None] = "501141005151"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "modelusagelog", sa.Column("conversation_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        "fk_modelusagelog_conversation",
        "modelusagelog",
        "conversation",
        ["conversation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_modelusagelog_conversation", "modelusagelog", type_="foreignkey"
    )
    op.drop_column("modelusagelog", "conversation_id")
    op.drop_table("conversation")
    # ### end Alembic commands ###
