"""update conversation with feature tag and metadata

Revision ID: ac7768abf755
Revises: ba449f0d2f98
Create Date: 2026-03-09 17:38:04.551940

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac7768abf755"
down_revision: Union[str, Sequence[str], None] = "ba449f0d2f98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "feature",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="chat",
            nullable=False,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "parameters")
    op.drop_column("conversation", "feature")
    # ### end Alembic commands ###
