"""file knowledge base on delete

Revision ID: ba449f0d2f98
Revises: 8676dc61378a
Create Date: 2026-03-09 10:17:35.560119

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba449f0d2f98"
down_revision: Union[str, Sequence[str], None] = "8676dc61378a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fileknowledgebaselink_knowledge_base_id_fkey"),
        "fileknowledgebaselink",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fileknowledgebaselink_file_id_fkey"),
        "fileknowledgebaselink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_knowledgebase_file",
        "fileknowledgebaselink",
        "knowledgebase",
        ["knowledge_base_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_file_knowledgebase",
        "fileknowledgebaselink",
        "file",
        ["file_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_knowledgebase_file", "fileknowledgebaselink", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_file_knowledgebase", "fileknowledgebaselink", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fileknowledgebaselink_file_id_fkey"),
        "fileknowledgebaselink",
        "file",
        ["file_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fileknowledgebaselink_knowledge_base_id_fkey"),
        "fileknowledgebaselink",
        "knowledgebase",
        ["knowledge_base_id"],
        ["id"],
    )
    # ### end Alembic commands ###
