"""private file field

Revision ID: e85cc303b514
Revises: 7c9d8a2440ef
Create Date: 2026-03-03 10:27:19.935466

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e85cc303b514"
down_revision: Union[str, Sequence[str], None] = "7c9d8a2440ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("is_private", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "is_private")
    # ### end Alembic commands ###
